{% set name = "pennylane-lightning-kokkos" %}
{% set version = "0.30.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7c8f0e0431f8052993cd8033a316f53590c7bf5419445d0725e214b93cbc661b
  patches:
    - 0001-setup.patch
    - 0002-setup.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  script: |
    {{ PYTHON }} setup.py build_ext --define="PLKOKKOS_ENABLE_WARNINGS=OFF"
    {{ PYTHON }} setup.py bdist_wheel
    {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - kokkos =3.7
    - pip
    - pybind11
    - python
  run:
    - pennylane >=0.28
    - python
test:
  imports:
    - pennylane_lightning_kokkos
  commands:
    - python -c "import pennylane as qml; qml.about()"
    - pl-device-test --device lightning.kokkos --shots None --skip-ops
    - pl-device-test --device lightning.kokkos --shots 10000 --skip-ops
    - pip check
  requires:
    - setuptools
    - flaky
    - pip
    - pytest
    - pytest-mock
about:
  home: https://docs.pennylane.ai/projects/lightning-kokkos
  summary: The PennyLane-Lightning-Kokkos plugin extends the Pennylane-Lightning state-vector simulator written in C++, and offloads to the Kokkos library for accelerated circuit simulation.
  license: Apache-2.0
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE
  doc_url: https://docs.pennylane.ai/projects/lightning-kokkos/en/latest/devices.html
  dev_url: https://github.com/PennyLaneAI/pennylane-lightning-kokkos

extra:
  recipe-maintainers:
    - vincentmr
  feedstock-name: {{ name }}
