{% set name = "pennylane-lightning-kokkos" %}
{% set version = "0.34.0" %}
{% set build_num = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 398c3a1d4450a9f3e146204c22329da9adc3f83a1685ae69187f3b25f47824c0

build:
  number: {{ build_num }}
  skip: true  # [py==38 or win]
  script:
    - CMAKE_ARGS="-DPL_BACKEND=lightning_kokkos -DCMAKE_CXX_COMPILER_TARGET=arm64-apple-macos11 -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_SYSTEM_PROCESSOR=ARM64" {{ PYTHON }} -m pip install . --no-deps -vv  # [osx and build_platform != target_platform]
    - PL_BACKEND=lightning_kokkos {{ PYTHON }} -m pip install . --no-deps -vv  # [not osx or build_platform == target_platform]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - ninja
  host:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - kokkos >=4.0.0,<4.2.0
    - pip
    - pybind11
    - python
  run:
    - pennylane >=0.34
    - python
    - {{ pin_compatible('kokkos', min_pin='x.x.x', max_pin='x.x.x') }}
  run_constrained:
    - __cuda <0.0a0  # [cuda_compiler_version == "None"]
test:
  imports:
    - pennylane_lightning
    - pennylane_lightning.lightning_kokkos
    - pennylane_lightning.lightning_kokkos_ops  # [build_platform == target_platform]
  commands:
    - pypy --version 2> /dev/null || echo Using Python to run tests
    - pypy -c "import pennylane as qml; qml.about()" 2> /dev/null || echo PyPy not found
    - python -c "import pennylane as qml; qml.about()"
    - pl-device-test --help
    - pl-device-test --device lightning.kokkos --shots None --skip-ops
    - pl-device-test --device lightning.kokkos --shots 100000 --skip-ops
    - pip check
  requires:
    - flaky
    - pip
    - pytest
    - pytest-benchmark
    - pytest-mock
about:
  home: https://docs.pennylane.ai/projects/lightning-kokkos
  summary: The PennyLane-Lightning-Kokkos plugin extends the Pennylane-Lightning state-vector simulator written in C++, and offloads to the Kokkos library for accelerated circuit simulation.
  license: Apache-2.0
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE
  doc_url: https://docs.pennylane.ai/projects/lightning-kokkos/en/latest/devices.html
  dev_url: https://github.com/PennyLaneAI/pennylane-lightning-kokkos

extra:
  recipe-maintainers:
    - vincentmr
  feedstock-name: {{ name }}
